#:schema node_modules/wrangler/config-schema.json

name = "feibainewsnow"   # 可以改成你喜欢的项目名

compatibility_date = "2026-03-30"   # 建议保持今天或较新的日期

pages_build_output_dir = "dist/output/public"

# 如果你暂时不想用 D1 数据库，可以先不加下面这部分
# d1_databases = [
#   { binding = "DB", database_name = "你的数据库名称", database_id = "你的D1数据库ID" }
# ]

# 其他可选配置
vars = { }
