#:schema node_modules/wrangler/config-schema.json

name = "newsnow"

compatibility_date = "2026-03-31"

pages_build_output_dir = "dist/output/public"

# D1 数据库绑定（必须这样写）
#d1_databases = [
#  { binding = "DB", database_name = "newsnow-db", database_id = "8bb160aa-2077-48ce-b6de-07008d094ff5" }
#]

[[d1_databases]]
binding = "DB"
database_name = "newsnow-db"
database_id = "8bb160aa-2077-48ce-b6de-07008d094ff5"
